id: P004637
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3671
  title: ཆོས་མངོན་པ་མཛོད་ཀྱི་མཆན་འགྲེལ་ཤེས་བྱའི་མེ་ལོང
  author: ''
  volumes:
    f921f02dfcb940dbaff2bd8caa660f1f:
      image_group_id: I1KG3695
      title: ''
      volume_number: 1
      total_pages: 394
